//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diiezer2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat
    {
        public int Id { get; set; }
        public Nullable<int> Chanson { get; set; }
        public string Utilisateur { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Chanson Chanson1 { get; set; }
    }
}
