//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diiezer2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Chanson = new HashSet<Chanson>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NbChanson { get; set; }
        public string Titre { get; set; }
        public Nullable<int> Durée { get; set; }
        public Nullable<int> Artiste { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Style { get; set; }
        public string Cover { get; set; }
    
        public virtual Artiste Artiste1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chanson> Chanson { get; set; }
    }
}
