//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diiezer2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chanson
    {
        public int Id { get; set; }
        public Nullable<int> Durée { get; set; }
        public string Titre { get; set; }
        public Nullable<int> Album { get; set; }
        public Nullable<int> Note { get; set; }
        public string Musique { get; set; }
        public string Extrait { get; set; }
    
        public virtual Album Album1 { get; set; }
    }
}
