//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diiezer2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int Id { get; set; }
        public int IdChanson { get; set; }
        public string Texte { get; set; }
    
        public virtual Chanson Chanson { get; set; }
    }
}
