//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diiezer2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panier
    {
        public int Id { get; set; }
        public string Utilisateur { get; set; }
        public int Object { get; set; }
        public int IsAlbum { get; set; }
    }
}
